export const listCountries = [
  {
    country: "Afghanistan",
    iso2: "AF",
    iso3: "AFG",
    uN: 4,
    dialCode: 93,
  },
  {
    country: "Aland Islands",
    iso2: "AX",
    iso3: "ALA",
    uN: 248,
    dialCode: 358,
  },
  {
    country: "Albania",
    iso2: "AL",
    iso3: "ALB",
    uN: 8,
    dialCode: 355,
  },
  {
    country: "Algeria",
    iso2: "DZ",
    iso3: "DZA",
    uN: 12,
    dialCode: 213,
  },
  {
    country: "American Samoa",
    iso2: "AS",
    iso3: "ASM",
    uN: 16,
    dialCode: 1,
  },
  {
    country: "Andorra",
    iso2: "AD",
    iso3: "AND",
    uN: 20,
    dialCode: 376,
  },
  {
    country: "Angola",
    iso2: "AO",
    iso3: "AGO",
    uN: 24,
    dialCode: 244,
  },
  {
    country: "Anguilla",
    iso2: "AI",
    iso3: "AIA",
    uN: 660,
    dialCode: 1,
  },
  {
    country: "Antarctica",
    iso2: "AQ",
    iso3: "ATA",
    uN: 10,
    dialCode: 672,
  },
  {
    country: "Antigua and Barbuda",
    iso2: "AG",
    iso3: "ATG",
    uN: 28,
    dialCode: 1,
  },
  {
    country: "Argentina",
    iso2: "AR",
    iso3: "ARG",
    uN: 32,
    dialCode: 54,
  },
  {
    country: "Armenia",
    iso2: "AM",
    iso3: "ARM",
    uN: 51,
    dialCode: 374,
  },
  {
    country: "Aruba",
    iso2: "AW",
    iso3: "ABW",
    uN: 533,
    dialCode: 297,
  },
  {
    country: "Australia",
    iso2: "AU",
    iso3: "AUS",
    uN: 36,
    dialCode: 61,
  },
  {
    country: "Austria",
    iso2: "AT",
    iso3: "AUT",
    uN: 40,
    dialCode: 43,
  },
  {
    country: "Azerbaijan",
    iso2: "AZ",
    iso3: "AZE",
    uN: 31,
    dialCode: 994,
  },
  {
    country: "Bahamas",
    iso2: "BS",
    iso3: "BHS",
    uN: 44,
    dialCode: 1,
  },
  {
    country: "Bahrain",
    iso2: "BH",
    iso3: "BHR",
    uN: 48,
    dialCode: 973,
  },
  {
    country: "Bangladesh",
    iso2: "BD",
    iso3: "BGD",
    uN: 50,
    dialCode: 880,
  },
  {
    country: "Barbados",
    iso2: "BB",
    iso3: "BRB",
    uN: 52,
    dialCode: 1,
  },
  {
    country: "Belarus",
    iso2: "BY",
    iso3: "BLR",
    uN: 112,
    dialCode: 375,
  },
  {
    country: "Belgium",
    iso2: "BE",
    iso3: "BEL",
    uN: 56,
    dialCode: 32,
  },
  {
    country: "Belize",
    iso2: "BZ",
    iso3: "BLZ",
    uN: 84,
    dialCode: 501,
  },
  {
    country: "Benin",
    iso2: "BJ",
    iso3: "BEN",
    uN: 204,
    dialCode: 229,
  },
  {
    country: "Bermuda",
    iso2: "BM",
    iso3: "BMU",
    uN: 60,
    dialCode: 1,
  },
  {
    country: "Bhutan",
    iso2: "BT",
    iso3: "BTN",
    uN: 64,
    dialCode: 975,
  },
  {
    country: "Bolivia",
    iso2: "BO",
    iso3: "BOL",
    uN: 68,
    dialCode: 591,
  },
  {
    country: "Bosnia and Herzegovina",
    iso2: "BA",
    iso3: "BIH",
    uN: 70,
    dialCode: 387,
  },
  {
    country: "Botswana",
    iso2: "BW",
    iso3: "BWA",
    uN: 72,
    dialCode: 267,
  },
  {
    country: "Bouvet Island",
    iso2: "BV",
    iso3: "BVT",
    uN: 74,
    dialCode: 1,
  },
  {
    country: "Brazil",
    iso2: "BR",
    iso3: "BRA",
    uN: 76,
    dialCode: 55,
  },
  {
    country: "British Virgin Islands",
    iso2: "VG",
    iso3: "VGB",
    uN: 92,
    dialCode: 1,
  },
  {
    country: "British Indian Ocean Territory",
    iso2: "IO",
    iso3: "IOT",
    uN: 86,
    dialCode: 246,
  },
  {
    country: "Brunei Darussalam",
    iso2: "BN",
    iso3: "BRN",
    uN: 96,
    dialCode: 673,
  },
  {
    country: "Bulgaria",
    iso2: "BG",
    iso3: "BGR",
    uN: 100,
    dialCode: 359,
  },
  {
    country: "Burkina Faso",
    iso2: "BF",
    iso3: "BFA",
    uN: 854,
    dialCode: 226,
  },
  {
    country: "Burundi",
    iso2: "BI",
    iso3: "BDI",
    uN: 108,
    dialCode: 257,
  },
  {
    country: "Cambodia",
    iso2: "KH",
    iso3: "KHM",
    uN: 116,
    dialCode: 855,
  },
  {
    country: "Cameroon",
    iso2: "CM",
    iso3: "CMR",
    uN: 120,
    dialCode: 237,
  },
  {
    country: "Canada",
    iso2: "CA",
    iso3: "CAN",
    uN: 124,
    dialCode: 1,
  },
  {
    country: "Cape Verde",
    iso2: "CV",
    iso3: "CPV",
    uN: 132,
    dialCode: 238,
  },
  {
    country: "Cayman Islands",
    iso2: "KY",
    iso3: "CYM",
    uN: 136,
    dialCode: 1,
  },
  {
    country: "Central African Republic",
    iso2: "CF",
    iso3: "CAF",
    uN: 140,
    dialCode: 236,
  },
  {
    country: "Chad",
    iso2: "TD",
    iso3: "TCD",
    uN: 148,
    dialCode: 235,
  },
  {
    country: "Chile",
    iso2: "CL",
    iso3: "CHL",
    uN: 152,
    dialCode: 56,
  },
  {
    country: "China",
    iso2: "CN",
    iso3: "CHN",
    uN: 156,
    dialCode: 86,
  },
  {
    country: "Hong Kong",
    iso2: "HK",
    iso3: "HKG",
    uN: 344,
    dialCode: 852,
  },
  {
    country: "Macao",
    iso2: "MO",
    iso3: "MAC",
    uN: 446,
    dialCode: 853,
  },
  {
    country: "Christmas Island",
    iso2: "CX",
    iso3: "CXR",
    uN: 162,
    dialCode: 61,
  },
  {
    country: "Cocos (Keeling) Islands",
    iso2: "CC",
    iso3: "CCK",
    uN: 166,
    dialCode: 61,
  },
  {
    country: "Colombia",
    iso2: "CO",
    iso3: "COL",
    uN: 170,
    dialCode: 57,
  },
  {
    country: "Comoros",
    iso2: "KM",
    iso3: "COM",
    uN: 174,
    dialCode: 269,
  },
  {
    country: "Congo (Brazzaville)",
    iso2: "CG",
    iso3: "COG",
    uN: 178,
    dialCode: 242,
  },
  {
    country: "Congo, (Kinshasa)",
    iso2: "CD",
    iso3: "COD",
    uN: 180,
    dialCode: 243,
  },
  {
    country: "Cook Islands",
    iso2: "CK",
    iso3: "COK",
    uN: 184,
    dialCode: 682,
  },
  {
    country: "Costa Rica",
    iso2: "CR",
    iso3: "CRI",
    uN: 188,
    dialCode: 506,
  },
  {
    country: "Côte d'Ivoire",
    iso2: "CI",
    iso3: "CIV",
    uN: 384,
    dialCode: 225,
  },
  {
    country: "Croatia",
    iso2: "HR",
    iso3: "HRV",
    uN: 191,
    dialCode: 385,
  },
  {
    country: "Cuba",
    iso2: "CU",
    iso3: "CUB",
    uN: 192,
    dialCode: 53,
  },
  {
    country: "Cyprus",
    iso2: "CY",
    iso3: "CYP",
    uN: 196,
    dialCode: 357,
  },
  {
    country: "Czech Republic",
    iso2: "CZ",
    iso3: "CZE",
    uN: 203,
    dialCode: 420,
  },
  {
    country: "Denmark",
    iso2: "DK",
    iso3: "DNK",
    uN: 208,
    dialCode: 45,
  },
  {
    country: "Djibouti",
    iso2: "DJ",
    iso3: "DJI",
    uN: 262,
    dialCode: 253,
  },
  {
    country: "Dominica",
    iso2: "DM",
    iso3: "DMA",
    uN: 212,
    dialCode: 1,
  },
  {
    country: "Dominican Republic",
    iso2: "DO",
    iso3: "DOM",
    uN: 214,
    dialCode: 1,
  },
  {
    country: "Ecuador",
    iso2: "EC",
    iso3: "ECU",
    uN: 218,
    dialCode: 593,
  },
  {
    country: "Egypt",
    iso2: "EG",
    iso3: "EGY",
    uN: 818,
    dialCode: 20,
  },
  {
    country: "El Salvador",
    iso2: "SV",
    iso3: "SLV",
    uN: 222,
    dialCode: 503,
  },
  {
    country: "Equatorial Guinea",
    iso2: "GQ",
    iso3: "GNQ",
    uN: 226,
    dialCode: 240,
  },
  {
    country: "Eritrea",
    iso2: "ER",
    iso3: "ERI",
    uN: 232,
    dialCode: 291,
  },
  {
    country: "Estonia",
    iso2: "EE",
    iso3: "EST",
    uN: 233,
    dialCode: 372,
  },
  {
    country: "Ethiopia",
    iso2: "ET",
    iso3: "ETH",
    uN: 231,
    dialCode: 251,
  },
  {
    country: "Falkland Islands (Malvinas)",
    iso2: "FK",
    iso3: "FLK",
    uN: 238,
    dialCode: 500,
  },
  {
    country: "Faroe Islands",
    iso2: "FO",
    iso3: "FRO",
    uN: 234,
    dialCode: 298,
  },
  {
    country: "Fiji",
    iso2: "FJ",
    iso3: "FJI",
    uN: 242,
    dialCode: 679,
  },
  {
    country: "Finland",
    iso2: "FI",
    iso3: "FIN",
    uN: 246,
    dialCode: 358,
  },
  {
    country: "France",
    iso2: "FR",
    iso3: "FRA",
    uN: 250,
    dialCode: 33,
  },
  {
    country: "French Guiana",
    iso2: "GF",
    iso3: "GUF",
    uN: 254,
    dialCode: 594,
  },
  {
    country: "French Polynesia",
    iso2: "PF",
    iso3: "PYF",
    uN: 258,
    dialCode: 689,
  },
  {
    country: "French Southern Territories",
    iso2: "TF",
    iso3: "ATF",
    uN: 260,
    dialCode: 262,
  },
  {
    country: "Gabon",
    iso2: "GA",
    iso3: "GAB",
    uN: 266,
    dialCode: 241,
  },
  {
    country: "Gambia",
    iso2: "GM",
    iso3: "GMB",
    uN: 270,
    dialCode: 220,
  },
  {
    country: "Georgia",
    iso2: "GE",
    iso3: "GEO",
    uN: 268,
    dialCode: 995,
  },
  {
    country: "Germany",
    iso2: "DE",
    iso3: "DEU",
    uN: 276,
    dialCode: 49,
  },
  {
    country: "Ghana",
    iso2: "GH",
    iso3: "GHA",
    uN: 288,
    dialCode: 233,
  },
  {
    country: "Gibraltar",
    iso2: "GI",
    iso3: "GIB",
    uN: 292,
    dialCode: 350,
  },
  {
    country: "Greece",
    iso2: "GR",
    iso3: "GRC",
    uN: 300,
    dialCode: 30,
  },
  {
    country: "Greenland",
    iso2: "GL",
    iso3: "GRL",
    uN: 304,
    dialCode: 299,
  },
  {
    country: "Grenada",
    iso2: "GD",
    iso3: "GRD",
    uN: 308,
    dialCode: 1,
  },
  {
    country: "Guadeloupe",
    iso2: "GP",
    iso3: "GLP",
    uN: 312,
    dialCode: 590,
  },
  {
    country: "Guam",
    iso2: "GU",
    iso3: "GUM",
    uN: 316,
    dialCode: 1,
  },
  {
    country: "Guatemala",
    iso2: "GT",
    iso3: "GTM",
    uN: 320,
    dialCode: 502,
  },
  {
    country: "Guernsey",
    iso2: "GG",
    iso3: "GGY",
    uN: 831,
    dialCode: 44,
  },
  {
    country: "Guinea",
    iso2: "GN",
    iso3: "GIN",
    uN: 324,
    dialCode: 224,
  },
  {
    country: "Guinea-Bissau",
    iso2: "GW",
    iso3: "GNB",
    uN: 624,
    dialCode: 245,
  },
  {
    country: "Guyana",
    iso2: "GY",
    iso3: "GUY",
    uN: 328,
    dialCode: 592,
  },
  {
    country: "Haiti",
    iso2: "HT",
    iso3: "HTI",
    uN: 332,
    dialCode: 509,
  },
  {
    country: "Heard and Mcdonald Islands",
    iso2: "HM",
    iso3: "HMD",
    uN: 334,
    dialCode: 1,
  },
  {
    country: "Holy See (Vatican City State)",
    iso2: "VA",
    iso3: "VAT",
    uN: 336,
    dialCode: 379,
  },
  {
    country: "Honduras",
    iso2: "HN",
    iso3: "HND",
    uN: 340,
    dialCode: 504,
  },
  {
    country: "Hungary",
    iso2: "HU",
    iso3: "HUN",
    uN: 348,
    dialCode: 36,
  },
  {
    country: "Iceland",
    iso2: "IS",
    iso3: "ISL",
    uN: 352,
    dialCode: 354,
  },
  {
    country: "India",
    iso2: "IN",
    iso3: "IND",
    uN: 356,
    dialCode: 91,
  },
  {
    country: "Indonesia",
    iso2: "ID",
    iso3: "IDN",
    uN: 360,
    dialCode: 62,
  },
  {
    country: "Iran, Islamic Republic of",
    iso2: "IR",
    iso3: "IRN",
    uN: 364,
    dialCode: 98,
  },
  {
    country: "Iraq",
    iso2: "IQ",
    iso3: "IRQ",
    uN: 368,
    dialCode: 964,
  },
  {
    country: "Ireland",
    iso2: "IE",
    iso3: "IRL",
    uN: 372,
    dialCode: 353,
  },
  {
    country: "Isle of Man",
    iso2: "IM",
    iso3: "IMN",
    uN: 833,
    dialCode: 44,
  },
  {
    country: "Israel",
    iso2: "IL",
    iso3: "ISR",
    uN: 376,
    dialCode: 972,
  },
  {
    country: "Italy",
    iso2: "IT",
    iso3: "ITA",
    uN: 380,
    dialCode: 39,
  },
  {
    country: "Jamaica",
    iso2: "JM",
    iso3: "JAM",
    uN: 388,
    dialCode: 1,
  },
  {
    country: "Japan",
    iso2: "JP",
    iso3: "JPN",
    uN: 392,
    dialCode: 81,
  },
  {
    country: "Jersey",
    iso2: "JE",
    iso3: "JEY",
    uN: 832,
    dialCode: 44,
  },
  {
    country: "Jordan",
    iso2: "JO",
    iso3: "JOR",
    uN: 400,
    dialCode: 962,
  },
  {
    country: "Kazakhstan",
    iso2: "KZ",
    iso3: "KAZ",
    uN: 398,
    dialCode: 7,
  },
  {
    country: "Kenya",
    iso2: "KE",
    iso3: "KEN",
    uN: 404,
    dialCode: 254,
  },
  {
    country: "Kiribati",
    iso2: "KI",
    iso3: "KIR",
    uN: 296,
    dialCode: 686,
  },
  {
    country: "Korea, Democratic People's Republic of (North)",
    iso2: "KP",
    iso3: "PRK",
    uN: 408,
    dialCode: 850,
  },
  {
    country: "Korea, Republic of (South)",
    iso2: "KR",
    iso3: "KOR",
    uN: 410,
    dialCode: 82,
  },
  {
    country: "Kuwait",
    iso2: "KW",
    iso3: "KWT",
    uN: 414,
    dialCode: 965,
  },
  {
    country: "Kyrgyzstan",
    iso2: "KG",
    iso3: "KGZ",
    uN: 417,
    dialCode: 996,
  },
  {
    country: "Lao PDR",
    iso2: "LA",
    iso3: "LAO",
    uN: 418,
    dialCode: 856,
  },
  {
    country: "Latvia",
    iso2: "LV",
    iso3: "LVA",
    uN: 428,
    dialCode: 371,
  },
  {
    country: "Lebanon",
    iso2: "LB",
    iso3: "LBN",
    uN: 422,
    dialCode: 961,
  },
  {
    country: "Lesotho",
    iso2: "LS",
    iso3: "LSO",
    uN: 426,
    dialCode: 266,
  },
  {
    country: "Liberia",
    iso2: "LR",
    iso3: "LBR",
    uN: 430,
    dialCode: 231,
  },
  {
    country: "Libya",
    iso2: "LY",
    iso3: "LBY",
    uN: 434,
    dialCode: 218,
  },
  {
    country: "Liechtenstein",
    iso2: "LI",
    iso3: "LIE",
    uN: 438,
    dialCode: 423,
  },
  {
    country: "Lithuania",
    iso2: "LT",
    iso3: "LTU",
    uN: 440,
    dialCode: 370,
  },
  {
    country: "Luxembourg",
    iso2: "LU",
    iso3: "LUX",
    uN: 442,
    dialCode: 352,
  },
  {
    country: "Macedonia, Republic of",
    iso2: "MK",
    iso3: "MKD",
    uN: 807,
    dialCode: 389,
  },
  {
    country: "Madagascar",
    iso2: "MG",
    iso3: "MDG",
    uN: 450,
    dialCode: 261,
  },
  {
    country: "Malawi",
    iso2: "MW",
    iso3: "MWI",
    uN: 454,
    dialCode: 265,
  },
  {
    country: "Malaysia",
    iso2: "MY",
    iso3: "MYS",
    uN: 458,
    dialCode: 60,
  },
  {
    country: "Maldives",
    iso2: "MV",
    iso3: "MDV",
    uN: 462,
    dialCode: 960,
  },
  {
    country: "Mali",
    iso2: "ML",
    iso3: "MLI",
    uN: 466,
    dialCode: 223,
  },
  {
    country: "Malta",
    iso2: "MT",
    iso3: "MLT",
    uN: 470,
    dialCode: 356,
  },
  {
    country: "Marshall Islands",
    iso2: "MH",
    iso3: "MHL",
    uN: 584,
    dialCode: 692,
  },
  {
    country: "Martinique",
    iso2: "MQ",
    iso3: "MTQ",
    uN: 474,
    dialCode: 596,
  },
  {
    country: "Mauritania",
    iso2: "MR",
    iso3: "MRT",
    uN: 478,
    dialCode: 222,
  },
  {
    country: "Mauritius",
    iso2: "MU",
    iso3: "MUS",
    uN: 480,
    dialCode: 230,
  },
  {
    country: "Mayotte",
    iso2: "YT",
    iso3: "MYT",
    uN: 175,
    dialCode: 262,
  },
  {
    country: "Mexico",
    iso2: "MX",
    iso3: "MEX",
    uN: 484,
    dialCode: 52,
  },
  {
    country: "Micronesia, Federated States of",
    iso2: "FM",
    iso3: "FSM",
    uN: 583,
    dialCode: 691,
  },
  {
    country: "Moldova",
    iso2: "MD",
    iso3: "MDA",
    uN: 498,
    dialCode: 373,
  },
  {
    country: "Monaco",
    iso2: "MC",
    iso3: "MCO",
    uN: 492,
    dialCode: 377,
  },
  {
    country: "Mongolia",
    iso2: "MN",
    iso3: "MNG",
    uN: 496,
    dialCode: 976,
  },
  {
    country: "Montenegro",
    iso2: "ME",
    iso3: "MNE",
    uN: 499,
    dialCode: 382,
  },
  {
    country: "Montserrat",
    iso2: "MS",
    iso3: "MSR",
    uN: 500,
    dialCode: 1,
  },
  {
    country: "Morocco and Western Sahara",
    iso2: "MA",
    iso3: "MAR",
    uN: 504,
    dialCode: 212,
  },
  {
    country: "Mozambique",
    iso2: "MZ",
    iso3: "MOZ",
    uN: 508,
    dialCode: 258,
  },
  {
    country: "Myanmar",
    iso2: "MM",
    iso3: "MMR",
    uN: 104,
    dialCode: 95,
  },
  {
    country: "Namibia",
    iso2: "NA",
    iso3: "NAM",
    uN: 516,
    dialCode: 264,
  },
  {
    country: "Nauru",
    iso2: "NR",
    iso3: "NRU",
    uN: 520,
    dialCode: 674,
  },
  {
    country: "Nepal",
    iso2: "NP",
    iso3: "NPL",
    uN: 524,
    dialCode: 977,
  },
  {
    country: "Netherlands",
    iso2: "NL",
    iso3: "NLD",
    uN: 528,
    dialCode: 31,
  },
  {
    country: "Netherlands Antilles",
    iso2: "AN",
    iso3: "ANT",
    uN: 530,
    dialCode: 599,
  },
  {
    country: "New Caledonia",
    iso2: "NC",
    iso3: "NCL",
    uN: 540,
    dialCode: 687,
  },
  {
    country: "New Zealand",
    iso2: "NZ",
    iso3: "NZL",
    uN: 554,
    dialCode: 64,
  },
  {
    country: "Nicaragua",
    iso2: "NI",
    iso3: "NIC",
    uN: 558,
    dialCode: 505,
  },
  {
    country: "Niger",
    iso2: "NE",
    iso3: "NER",
    uN: 562,
    dialCode: 227,
  },
  {
    country: "Nigeria",
    iso2: "NG",
    iso3: "NGA",
    uN: 566,
    dialCode: 234,
  },
  {
    country: "Niue",
    iso2: "NU",
    iso3: "NIU",
    uN: 570,
    dialCode: 683,
  },
  {
    country: "Norfolk Island",
    iso2: "NF",
    iso3: "NFK",
    uN: 574,
    dialCode: 672,
  },
  {
    country: "Northern Mariana Islands",
    iso2: "MP",
    iso3: "MNP",
    uN: 580,
    dialCode: 1,
  },
  {
    country: "Norway",
    iso2: "NO",
    iso3: "NOR",
    uN: 578,
    dialCode: 47,
  },
  {
    country: "Oman",
    iso2: "OM",
    iso3: "OMN",
    uN: 512,
    dialCode: 968,
  },
  {
    country: "Pakistan",
    iso2: "PK",
    iso3: "PAK",
    uN: 586,
    dialCode: 92,
  },
  {
    country: "Palau",
    iso2: "PW",
    iso3: "PLW",
    uN: 585,
    dialCode: 680,
  },
  {
    country: "Palestinian Territory",
    iso2: "PS",
    iso3: "PSE",
    uN: 275,
    dialCode: 970,
  },
  {
    country: "Panama",
    iso2: "PA",
    iso3: "PAN",
    uN: 591,
    dialCode: 507,
  },
  {
    country: "Papua New Guinea",
    iso2: "PG",
    iso3: "PNG",
    uN: 598,
    dialCode: 675,
  },
  {
    country: "Paraguay",
    iso2: "PY",
    iso3: "PRY",
    uN: 600,
    dialCode: 595,
  },
  {
    country: "Peru",
    iso2: "PE",
    iso3: "PER",
    uN: 604,
    dialCode: 51,
  },
  {
    country: "Philippines",
    iso2: "PH",
    iso3: "PHL",
    uN: 608,
    dialCode: 63,
  },
  {
    country: "Pitcairn",
    iso2: "PN",
    iso3: "PCN",
    uN: 612,
    dialCode: 870,
  },
  {
    country: "Poland",
    iso2: "PL",
    iso3: "POL",
    uN: 616,
    dialCode: 48,
  },
  {
    country: "Portugal",
    iso2: "PT",
    iso3: "PRT",
    uN: 620,
    dialCode: 351,
  },
  {
    country: "Puerto Rico",
    iso2: "PR",
    iso3: "PRI",
    uN: 630,
    dialCode: 1,
  },
  {
    country: "Qatar",
    iso2: "QA",
    iso3: "QAT",
    uN: 634,
    dialCode: 974,
  },
  {
    country: "Réunion and Mayotte",
    iso2: "RE",
    iso3: "REU",
    uN: 638,
    dialCode: 262,
  },
  {
    country: "Romania",
    iso2: "RO",
    iso3: "ROU",
    uN: 642,
    dialCode: 40,
  },
  {
    country: "Russian Federation",
    iso2: "RU",
    iso3: "RUS",
    uN: 643,
    dialCode: 7,
  },
  {
    country: "Rwanda",
    iso2: "RW",
    iso3: "RWA",
    uN: 646,
    dialCode: 250,
  },
  {
    country: "Saint-Barthélemy",
    iso2: "BL",
    iso3: "BLM",
    uN: 652,
    dialCode: 590,
  },
  {
    country: "Saint Helena",
    iso2: "SH",
    iso3: "SHN",
    uN: 654,
    dialCode: 290,
  },
  {
    country: "Saint Kitts and Nevis",
    iso2: "KN",
    iso3: "KNA",
    uN: 659,
    dialCode: 1,
  },
  {
    country: "Saint Lucia",
    iso2: "LC",
    iso3: "LCA",
    uN: 662,
    dialCode: 1,
  },
  {
    country: "Saint-Martin (French part)",
    iso2: "MF",
    iso3: "MAF",
    uN: 663,
    dialCode: 599,
  },
  {
    country: "Saint Pierre and Miquelon",
    iso2: "PM",
    iso3: "SPM",
    uN: 666,
    dialCode: 508,
  },
  {
    country: "Saint Vincent and Grenadines",
    iso2: "VC",
    iso3: "VCT",
    uN: 670,
    dialCode: 1,
  },
  {
    country: "Samoa",
    iso2: "WS",
    iso3: "WSM",
    uN: 882,
    dialCode: 685,
  },
  {
    country: "San Marino",
    iso2: "SM",
    iso3: "SMR",
    uN: 674,
    dialCode: 378,
  },
  {
    country: "Sao Tome and Principe",
    iso2: "ST",
    iso3: "STP",
    uN: 678,
    dialCode: 239,
  },
  {
    country: "Saudi Arabia",
    iso2: "SA",
    iso3: "SAU",
    uN: 682,
    dialCode: 966,
  },
  {
    country: "Senegal",
    iso2: "SN",
    iso3: "SEN",
    uN: 686,
    dialCode: 221,
  },
  {
    country: "Serbia",
    iso2: "RS",
    iso3: "SRB",
    uN: 688,
    dialCode: 381,
  },
  {
    country: "Seychelles",
    iso2: "SC",
    iso3: "SYC",
    uN: 690,
    dialCode: 248,
  },
  {
    country: "Sierra Leone",
    iso2: "SL",
    iso3: "SLE",
    uN: 694,
    dialCode: 232,
  },
  {
    country: "Singapore",
    iso2: "SG",
    iso3: "SGP",
    uN: 702,
    dialCode: 65,
  },
  {
    country: "Slovakia",
    iso2: "SK",
    iso3: "SVK",
    uN: 703,
    dialCode: 421,
  },
  {
    country: "Slovenia",
    iso2: "SI",
    iso3: "SVN",
    uN: 705,
    dialCode: 386,
  },
  {
    country: "Solomon Islands",
    iso2: "SB",
    iso3: "SLB",
    uN: 90,
    dialCode: 677,
  },
  {
    country: "Somalia",
    iso2: "SO",
    iso3: "SOM",
    uN: 706,
    dialCode: 252,
  },
  {
    country: "South Africa",
    iso2: "ZA",
    iso3: "ZAF",
    uN: 710,
    dialCode: 27,
  },
  {
    country: "South Georgia and the South Sandwich Islands",
    iso2: "GS",
    iso3: "SGS",
    uN: 239,
    dialCode: 500,
  },
  {
    country: "South Sudan",
    iso2: "SS",
    iso3: "SSD",
    uN: 728,
    dialCode: 211,
  },
  {
    country: "Spain",
    iso2: "ES",
    iso3: "ESP",
    uN: 724,
    dialCode: 34,
  },
  {
    country: "Sri Lanka",
    iso2: "LK",
    iso3: "LKA",
    uN: 144,
    dialCode: 94,
  },
  {
    country: "Sudan",
    iso2: "SD",
    iso3: "SDN",
    uN: 736,
    dialCode: 249,
  },
  {
    country: "Suriname",
    iso2: "SR",
    iso3: "SUR",
    uN: 740,
    dialCode: 597,
  },
  {
    country: "Svalbard and Jan Mayen Islands",
    iso2: "SJ",
    iso3: "SJM",
    uN: 744,
    dialCode: 47,
  },
  {
    country: "Swaziland",
    iso2: "SZ",
    iso3: "SWZ",
    uN: 748,
    dialCode: 268,
  },
  {
    country: "Sweden",
    iso2: "SE",
    iso3: "SWE",
    uN: 752,
    dialCode: 46,
  },
  {
    country: "Switzerland",
    iso2: "CH",
    iso3: "CHE",
    uN: 756,
    dialCode: 41,
  },
  {
    country: "Syrian Arab Republic (Syria)",
    iso2: "SY",
    iso3: "SYR",
    uN: 760,
    dialCode: 963,
  },
  {
    country: "Taiwan",
    iso2: "TW",
    iso3: "TWN",
    uN: 158,
    dialCode: 886,
  },
  {
    country: "Tajikistan",
    iso2: "TJ",
    iso3: "TJK",
    uN: 762,
    dialCode: 992,
  },
  {
    country: "Tanzania, United Republic of",
    iso2: "TZ",
    iso3: "TZA",
    uN: 834,
    dialCode: 255,
  },
  {
    country: "Thailand",
    iso2: "TH",
    iso3: "THA",
    uN: 764,
    dialCode: 66,
  },
  {
    country: "Timor-Leste",
    iso2: "TL",
    iso3: "TLS",
    uN: 626,
    dialCode: 670,
  },
  {
    country: "Togo",
    iso2: "TG",
    iso3: "TGO",
    uN: 768,
    dialCode: 228,
  },
  {
    country: "Tokelau",
    iso2: "TK",
    iso3: "TKL",
    uN: 772,
    dialCode: 690,
  },
  {
    country: "Tonga",
    iso2: "TO",
    iso3: "TON",
    uN: 776,
    dialCode: 676,
  },
  {
    country: "Trinidad and Tobago",
    iso2: "TT",
    iso3: "TTO",
    uN: 780,
    dialCode: 1,
  },
  {
    country: "Tunisia",
    iso2: "TN",
    iso3: "TUN",
    uN: 788,
    dialCode: 216,
  },
  {
    country: "Turkey",
    iso2: "TR",
    iso3: "TUR",
    uN: 792,
    dialCode: 90,
  },
  {
    country: "Turkmenistan",
    iso2: "TM",
    iso3: "TKM",
    uN: 795,
    dialCode: 993,
  },
  {
    country: "Turks and Caicos Islands",
    iso2: "TC",
    iso3: "TCA",
    uN: 796,
    dialCode: 1,
  },
  {
    country: "Tuvalu",
    iso2: "TV",
    iso3: "TUV",
    uN: 798,
    dialCode: 688,
  },
  {
    country: "Uganda",
    iso2: "UG",
    iso3: "UGA",
    uN: 800,
    dialCode: 256,
  },
  {
    country: "Ukraine",
    iso2: "UA",
    iso3: "UKR",
    uN: 804,
    dialCode: 380,
  },
  {
    country: "United Arab Emirates",
    iso2: "AE",
    iso3: "ARE",
    uN: 784,
    dialCode: 971,
  },
  {
    country: "United Kingdom",
    iso2: "GB",
    iso3: "GBR",
    uN: 826,
    dialCode: 44,
  },
  {
    country: "United States of America",
    iso2: "US",
    iso3: "USA",
    uN: 840,
    dialCode: 1,
  },
  {
    country: "US Minor Outlying Islands",
    iso2: "UM",
    iso3: "UMI",
    uN: 581,
    dialCode: 246,
  },
  {
    country: "Uruguay",
    iso2: "UY",
    iso3: "URY",
    uN: 858,
    dialCode: 598,
  },
  {
    country: "Uzbekistan",
    iso2: "UZ",
    iso3: "UZB",
    uN: 860,
    dialCode: 998,
  },
  {
    country: "Vanuatu",
    iso2: "VU",
    iso3: "VUT",
    uN: 548,
    dialCode: 678,
  },
  {
    country: "Venezuela (Bolivarian Republic)",
    iso2: "VE",
    iso3: "VEN",
    uN: 862,
    dialCode: 58,
  },
  {
    country: "Viet Nam",
    iso2: "VN",
    iso3: "VNM",
    uN: 704,
    dialCode: 84,
  },
  {
    country: "Virgin Islands, US",
    iso2: "VI",
    iso3: "VIR",
    uN: 850,
    dialCode: 1,
  },
  {
    country: "Wallis and Futuna Islands",
    iso2: "WF",
    iso3: "WLF",
    uN: 876,
    dialCode: 681,
  },
  {
    country: "Western Sahara",
    iso2: "EH",
    iso3: "ESH",
    uN: 732,
    dialCode: 212,
  },
  {
    country: "Yemen",
    iso2: "YE",
    iso3: "YEM",
    uN: 887,
    dialCode: 967,
  },
  {
    country: "Zambia",
    iso2: "ZM",
    iso3: "ZMB",
    uN: 894,
    dialCode: 260,
  },
  {
    country: "Zimbabwe",
    iso2: "ZW",
    iso3: "ZWE",
    uN: 716,
    dialCode: 263,
  },
];
